"""add length

Revision ID: 015e6edeccb7
Revises: c18a5b531790
Create Date: 2022-04-10 06:26:50.685694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015e6edeccb7'
down_revision = 'c18a5b531790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies_basic', sa.Column('length', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies_basic', 'length')
    # ### end Alembic commands ###
