"""eventname unique

Revision ID: 0b62ca3ad65f
Revises: fc4ce1cd7eda
Create Date: 2022-04-03 23:33:16.041323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b62ca3ad65f'
down_revision = 'fc4ce1cd7eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_title', table_name='events')
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.create_index('ix_events_title', 'events', ['title'], unique=False)
    # ### end Alembic commands ###
