"""first

Revision ID: 796e13f1aad7
Revises: 
Create Date: 2022-04-02 14:33:27.152074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796e13f1aad7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('comname', sa.String(length=64), nullable=True),
    sa.Column('wishpoint', sa.Integer(), nullable=True),
    sa.Column('step', sa.String(length=64), nullable=True),
    sa.Column('scale', sa.Integer(), nullable=True),
    sa.Column('startmoney', sa.Integer(), nullable=True),
    sa.Column('numemploy', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_comname'), 'companies', ['comname'], unique=False)
    op.create_index(op.f('ix_companies_from_user_id'), 'companies', ['from_user_id'], unique=False)
    op.create_table('companies_basic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('comname', sa.String(length=64), nullable=True),
    sa.Column('occupation', sa.String(length=64), nullable=True),
    sa.Column('length', sa.String(length=64), nullable=True),
    sa.Column('scale', sa.String(length=64), nullable=True),
    sa.Column('comstock', sa.String(length=64), nullable=True),
    sa.Column('supplier', sa.String(length=64), nullable=True),
    sa.Column('client', sa.String(length=64), nullable=True),
    sa.Column('is_active_step', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_basic_comname'), 'companies_basic', ['comname'], unique=True)
    op.create_index(op.f('ix_companies_basic_from_user_id'), 'companies_basic', ['from_user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), server_default='<function uuid4 at 0x0000025A2B3C71F0>', nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('taskname', sa.String(length=64), nullable=True),
    sa.Column('workday', sa.DateTime(), nullable=True),
    sa.Column('overday', sa.DateTime(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_from_user_id'), 'tasks', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_tasks_taskname'), 'tasks', ['taskname'], unique=False)
    op.create_table('companies_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('basic_id', sa.Integer(), nullable=True),
    sa.Column('comname', sa.String(length=64), nullable=True),
    sa.Column('aspiration', sa.Integer(), nullable=True),
    sa.Column('step', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('good_comment', sa.Text(), nullable=True),
    sa.Column('bad_comment', sa.Text(), nullable=True),
    sa.Column('sonota_comment', sa.Text(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['basic_id'], ['companies_basic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_step_basic_id'), 'companies_step', ['basic_id'], unique=False)
    op.create_index(op.f('ix_companies_step_comname'), 'companies_step', ['comname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_step_comname'), table_name='companies_step')
    op.drop_index(op.f('ix_companies_step_basic_id'), table_name='companies_step')
    op.drop_table('companies_step')
    op.drop_index(op.f('ix_tasks_taskname'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_from_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_companies_basic_from_user_id'), table_name='companies_basic')
    op.drop_index(op.f('ix_companies_basic_comname'), table_name='companies_basic')
    op.drop_table('companies_basic')
    op.drop_index(op.f('ix_companies_from_user_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_comname'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
