"""add basic_number

Revision ID: 1bb7dc8d7098
Revises: 0b62ca3ad65f
Create Date: 2022-04-10 06:17:49.108276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb7dc8d7098'
down_revision = '0b62ca3ad65f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('basic_id', sa.Integer(), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('comname', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('capital', sa.Integer(), nullable=True),
    sa.Column('employee', sa.Integer(), nullable=True),
    sa.Column('turnover', sa.Integer(), nullable=True),
    sa.Column('start_salary', sa.Integer(), nullable=True),
    sa.Column('average_salary', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['basic_id'], ['companies_basic.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_numbers_basic_id'), 'company_numbers', ['basic_id'], unique=False)
    op.create_index(op.f('ix_company_numbers_comname'), 'company_numbers', ['comname'], unique=True)
    op.create_index(op.f('ix_company_numbers_from_user_id'), 'company_numbers', ['from_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_numbers_from_user_id'), table_name='company_numbers')
    op.drop_index(op.f('ix_company_numbers_comname'), table_name='company_numbers')
    op.drop_index(op.f('ix_company_numbers_basic_id'), table_name='company_numbers')
    op.drop_table('company_numbers')
    # ### end Alembic commands ###
