"""test eventcolor

Revision ID: ea552f9f6874
Revises: 015e6edeccb7
Create Date: 2022-07-29 00:35:51.873429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea552f9f6874'
down_revision = '015e6edeccb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('basic_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('allDayCheck', sa.Boolean(), nullable=True),
    sa.Column('at_start', sa.DateTime(), nullable=True),
    sa.Column('at_end', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('eventcolor', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['basic_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_2_basic_id'), 'events_2', ['basic_id'], unique=False)
    op.create_index(op.f('ix_events_2_title'), 'events_2', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_2_title'), table_name='events_2')
    op.drop_index(op.f('ix_events_2_basic_id'), table_name='events_2')
    op.drop_table('events_2')
    # ### end Alembic commands ###
