"""add eventTable

Revision ID: fc4ce1cd7eda
Revises: 796e13f1aad7
Create Date: 2022-04-03 23:28:01.282266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4ce1cd7eda'
down_revision = '796e13f1aad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('basic_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('allDayCheck', sa.Boolean(), nullable=True),
    sa.Column('at_start', sa.DateTime(), nullable=True),
    sa.Column('at_end', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['basic_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_basic_id'), 'events', ['basic_id'], unique=False)
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_index(op.f('ix_events_basic_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
